import type { SlashCommandSpec } from "./types";

export const BUILTIN_AGY_COMPAT_SLASH_COMMANDS: ReadonlyArray<SlashCommandSpec> = [
	{
		name: "learn",
		icon: "memory",
		description: "Start the learning workflow to persist reusable behaviors (agy compat)",
		inlineHint: "[optional context]",
		allowArgs: true,
		handle: async (command, _runtime) => {
			const base = `<LEARN>\nThe user invoked /learn to persist reusable behaviors from recent interactions, corrections, or successes. Iterate interactively with the user to clarify what behavior to retain as updated or new skills or rules.\n## Identify What to Learn\n1. **Analyze User Messages**: Prioritize analyzing recent user messages for explicit corrections, constraints, overrides, or pointers (e.g., "no", "instead", "that failed").\n2. **Identify the Fix**: Compare failed attempts with the successful resolution to isolate the pivotal change.\n3. **Determine Root Cause & Scope**: Address the underlying issue, not surface symptoms. Determine if it's universal or domain-specific.\n4. **Verify if learning is needed**: If the interaction did not reveal any new reusable behaviors or constraints, explain this to the user and exit without proposing changes.\n2. Create/update a learning_proposal.md artifact outlining your classification, rationale, and precise text additions/diffs.\n</LEARN>`;
			const prompt = command.args ? `${base}\n\n${command.args.trim()}` : base;
			return { prompt };
		},
		handleTui: async (command, runtime) => {
			runtime.ctx.editor.setText("");
			const base = `<LEARN>\nThe user invoked /learn to persist reusable behaviors from recent interactions, corrections, or successes. Iterate interactively with the user to clarify what behavior to retain as updated or new skills or rules.\n## Identify What to Learn\n1. **Analyze User Messages**: Prioritize analyzing recent user messages for explicit corrections, constraints, overrides, or pointers (e.g., "no", "instead", "that failed").\n2. **Identify the Fix**: Compare failed attempts with the successful resolution to isolate the pivotal change.\n3. **Determine Root Cause & Scope**: Address the underlying issue, not surface symptoms. Determine if it's universal or domain-specific.\n4. **Verify if learning is needed**: If the interaction did not reveal any new reusable behaviors or constraints, explain this to the user and exit without proposing changes.\n2. Create/update a learning_proposal.md artifact outlining your classification, rationale, and precise text additions/diffs.\n</LEARN>`;
			const prompt = command.args ? `${base}\n\n${command.args.trim()}` : base;
			return { prompt };
		},
	},
	{
		name: "teamwork-preview",
		aliases: ["teamwork"],
		icon: "agents",
		description: "Start the teamwork preview workflow (agy compat)",
		inlineHint: "[optional context]",
		allowArgs: true,
		handle: async (command, _runtime) => {
			const base = `<TEAMWORK>\nThe user invoked /teamwork-preview to run an autonomous multi-agent teamwork project (agy compatibility & enhanced execution).\nYou are the **Teamwork Sentinel (Project Director)**.\n\n## Autonomous Execution Directive\n1. **Zero Questionnaire Traps**:\n   - DO NOT trap the user in an interactive 9-step survey or ask unnecessary questions.\n   - If a request/task is provided with the command:\n     - Rapidly ground yourself: perform 1-2 quick reads/globs if needed to inspect relevant project files or endpoints.\n     - Scaffold the coordination files:\n       - \`.agents/ORIGINAL_REQUEST.md\`: Record the formal request, numbered requirements (R1..Rn), and concrete acceptance criteria (C1..Cn).\n       - \`prompt_draft.md\`: Keep a living summary (Description, Working directory, Requirements, Acceptance Criteria, Status: Launched).\n     - If the user gave an actionable directive (e.g. "khám phá", "triển khai", "làm đi", "chạy đi", "start", "fix"), or after 1 single concise confirmation via \`ask\` (Recommended: "Phê duyệt kế hoạch và khởi chạy ngay!"), proceed IMMEDIATELY to multi-agent execution.\n   - If invoked without arguments: ask the user in 1 concise sentence what project or task to execute.\n\n2. **Multi-Agent Team Delegation Protocol**:\n   - Delegate the heavy lifting to the Teamwork Multi-Agent Team using the \`task\` tool:\n     - Spawn \`teamwork-orchestrator\` (aliases: \`teamwork_preview_orchestrator\`, \`teamwork\`) to lead the project:\n       \`\`\`json\n       task(tasks=[{\n         "name": "TeamworkOrchestrator",\n         "agent": "teamwork-orchestrator",\n         "task": "Lead project execution for the approved requirements in .agents/ORIGINAL_REQUEST.md..."\n       }])\n       \`\`\`\n     - Alternatively, spawn specialized cohorts directly:\n       - Phase 0: \`teamwork-explorer\` cohort for parallel reconnaissance & architecture survey.\n       - Phase 1: \`teamwork-worker\` cohort for implementation, database migrations, and testing.\n       - Phase 2: \`teamwork-reviewer\` & \`teamwork-challenger\` for spec review and adversarial stress-testing.\n       - Phase 3: \`teamwork-auditor\` (forensic audit, non-skippable, enforces zero fake mocks and real test output).\n       - Phase 4: \`teamwork-victory-auditor\` for final independent victory certification.\n\n3. **Coordination & Blackboard Protocol**:\n   - Maintain the project coordination space in \`.agents/\`:\n     - \`.agents/ORIGINAL_REQUEST.md\` (authoritative task spec).\n     - \`.agents/<agent_name>/BRIEFING.md\`, \`plan.md\`, \`progress.md\`, \`handoff.md\`.\n   - Subagents coordinate and hand off work using \`hub(op="send", to="...")\`.\n   - Sentinel monitors progress and reports concise milestones to the user:\n     \`[Sentinel Progress Report - Iteration N]\`\n   - NEVER report final completion until the \`teamwork-victory-auditor\` has issued \`VICTORY CONFIRMED\`.\n</TEAMWORK>`;
			const prompt = command.args ? `${base}\n\n${command.args.trim()}` : base;
			return { prompt };
		},
		handleTui: async (command, runtime) => {
			runtime.ctx.editor.setText("");
			const base = `<TEAMWORK>\nThe user invoked /teamwork-preview to run an autonomous multi-agent teamwork project (agy compatibility & enhanced execution).\nYou are the **Teamwork Sentinel (Project Director)**.\n\n## Autonomous Execution Directive\n1. **Zero Questionnaire Traps**:\n   - DO NOT trap the user in an interactive 9-step survey or ask unnecessary questions.\n   - If a request/task is provided with the command:\n     - Rapidly ground yourself: perform 1-2 quick reads/globs if needed to inspect relevant project files or endpoints.\n     - Scaffold the coordination files:\n       - \`.agents/ORIGINAL_REQUEST.md\`: Record the formal request, numbered requirements (R1..Rn), and concrete acceptance criteria (C1..Cn).\n       - \`prompt_draft.md\`: Keep a living summary (Description, Working directory, Requirements, Acceptance Criteria, Status: Launched).\n     - If the user gave an actionable directive (e.g. "khám phá", "triển khai", "làm đi", "chạy đi", "start", "fix"), or after 1 single concise confirmation via \`ask\` (Recommended: "Phê duyệt kế hoạch và khởi chạy ngay!"), proceed IMMEDIATELY to multi-agent execution.\n   - If invoked without arguments: ask the user in 1 concise sentence what project or task to execute.\n\n2. **Multi-Agent Team Delegation Protocol**:\n   - Delegate the heavy lifting to the Teamwork Multi-Agent Team using the \`task\` tool:\n     - Spawn \`teamwork-orchestrator\` (aliases: \`teamwork_preview_orchestrator\`, \`teamwork\`) to lead the project:\n       \`\`\`json\n       task(tasks=[{\n         "name": "TeamworkOrchestrator",\n         "agent": "teamwork-orchestrator",\n         "task": "Lead project execution for the approved requirements in .agents/ORIGINAL_REQUEST.md..."\n       }])\n       \`\`\`\n     - Alternatively, spawn specialized cohorts directly:\n       - Phase 0: \`teamwork-explorer\` cohort for parallel reconnaissance & architecture survey.\n       - Phase 1: \`teamwork-worker\` cohort for implementation, database migrations, and testing.\n       - Phase 2: \`teamwork-reviewer\` & \`teamwork-challenger\` for spec review and adversarial stress-testing.\n       - Phase 3: \`teamwork-auditor\` (forensic audit, non-skippable, enforces zero fake mocks and real test output).\n       - Phase 4: \`teamwork-victory-auditor\` for final independent victory certification.\n\n3. **Coordination & Blackboard Protocol**:\n   - Maintain the project coordination space in \`.agents/\`:\n     - \`.agents/ORIGINAL_REQUEST.md\` (authoritative task spec).\n     - \`.agents/<agent_name>/BRIEFING.md\`, \`plan.md\`, \`progress.md\`, \`handoff.md\`.\n   - Subagents coordinate and hand off work using \`hub(op="send", to="...")\`.\n   - Sentinel monitors progress and reports concise milestones to the user:\n     \`[Sentinel Progress Report - Iteration N]\`\n   - NEVER report final completion until the \`teamwork-victory-auditor\` has issued \`VICTORY CONFIRMED\`.\n</TEAMWORK>`;
			const prompt = command.args ? `${base}\n\n${command.args.trim()}` : base;
			return { prompt };
		},
	},
];
